### ISSUE TITLE
A general question about the FID metric

### ISSUE THREAD

**Issue by sandylaker** [open-mmlab/mmgeneration#97]
Hi,

I would like to ask a general question about the FID metric. If we train the CycleGAN on another dataset that is much different from the ImageNet dataset, e.g. a MRI dataset, do we need to re-train the Inception-V3 model in advance? I appreciate your help.

**Comment by plyfager** [comment]
Hi @[sandylaker](https://github.com/sandylaker), there is no need to re-train the inception model. Four your purpose, following these three steps to get the `FID` metric.
Step 1
Using [inception_stat.py](https://github.com/open-mmlab/mmgeneration/blob/master/tools/utils/inception_stat.py) to get the inception stat pickle.
````
python tools/utils/inception_stat.py --data-cfg {DATA_CONFIG} --pklname {PKL_NAME} --inception-style stylegan --num-samples {NUM_SAMPLES}
```
Here, if your dataset is very large, I suggest you set `NUM_SAMPLES` to 50000. Otherwise, you can just set it to the size of the whole test set.

Step 2
Add the following code to your config file.
```
metrics = dict(
    fid50k=dict(
        type='FID',
        num_images={NUM_SAMPLES}, 
        inception_pkl={path of inception_pkl},
        inception_args=dict(type='StyleGAN')))
```

Step 3
Using [translation_eval.py](https://github.com/open-mmlab/mmgeneration/blob/master/tools/utils/translation_eval.py) to eval your model.
```
python tools/utils/translation_eval.py {CONFIG} {CKPT} --batch-size {BATCH_SIZE}
```
